### ISSUE TITLE
GetText.NET.Extractor:  bug, if the backslash (\) in a string

### ISSUE THREAD

**Issue by mcka-dev** [perpetualKid/GetText.NET#17]
Hi
in GetText.NET.Extractor v0.9.6.0 

**Source:**
```
using System;
using System.Windows.Forms;

namespace HelloApp
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent()

            button1.Text = "Action: \"Operator Assistant\"";
        }
    }
}
```

**Actual result:**
![изображение](https://user-images.githubusercontent.com/16173503/98964999-8d9a2900-251a-11eb-8736-1bf5c14d5994.png)
If I combine `ru.mo` and `Messages. pot` I'll get an error
![изображение](https://user-images.githubusercontent.com/16173503/98965186-cb974d00-251a-11eb-96f4-c1c17aa647be.png)

**Expected Result:**
![изображение](https://user-images.githubusercontent.com/16173503/98965052-9f7bcc00-251a-11eb-808d-3ed95ae11b72.png)
![изображение](https://user-images.githubusercontent.com/16173503/98965625-4fe9d000-251b-11eb-80da-2c407b661ef4.png)

**Comment by perpetualKid** [comment]
looking into this. 
However, PoEdit itself doesn't complain on this.

**Comment by perpetualKid** [comment]
some more testing, seems the GNU commandline tools are more peculiar and not as relaxed as Windows-based tools, thus need more strict escaping. I need to check first what other characters need escaping before implementing any changes.
