### ISSUE TITLE
ObjectListView columns' header title doesn't localize

### ISSUE THREAD

**Issue by a-sanders** [perpetualKid/GetText.NET#21]
Hello,
I faced the issue when the Extractor got all columns' headers successfully but in the runtime, Localizer doesn't localize headers.

I mean the [ObjectListView ](https://www.nuget.org/packages/ObjectListView.Official/2.9.1) package.

Regards.

**Comment by perpetualKid** [comment]
can you please provide a simple sample project @a-sanders

**Comment by a-sanders** [comment]
> 
> 
> can you please provide a simple sample project @a-sanders
Yes, I can. Check it, please.

[TestGetTextOLV.zip](https://github.com/perpetualKid/GetText.NET/files/6035265/TestGetTextOLV.zip)

**Comment by perpetualKid** [comment]
the Localizer isn't currently handling ListView control's headers, but fortunately that is easy to fix:
![image](https://user-images.githubusercontent.com/7158903/108994828-8e576500-769c-11eb-9fc2-52d66945d5c5.png)

I'm implementing this, will need to test and prepare a new package to build (likely v0.9.8). I'll submit the code in a short while, but getting the package published may take another day

**Comment by perpetualKid** [comment]
https://www.nuget.org/packages/GetText.NET/0.9.8
