### ISSUE TITLE
ContextMenuStrip is not localized

### ISSUE THREAD

**Issue by a-sanders** [perpetualKid/GetText.NET#27]
ContextMenuStrip isn't localized when Form localizing
            Localizer.Localize(form, catalog);

But it works as expected on direct call Localize for the contextMenuStrip:
            Localizer.Localize(contextMenuStrip);

Bug?

**Comment by a-sanders** [comment]
The ContextMenuStrip does not have a Parent property, unlike MenuStrip, and it can be found exactly in the Form.Components list.
So it can be handled in the Localizer.IterateToolStripItems like as other components (the only ToolTip in the 0.9.8 version).
Probably it would be good to have ComponentsList for all components instead of ToolTips for tooltip controls only and switch by component class in the LocalizableObjectAdapter.

**Comment by perpetualKid** [comment]
in call to 
```cshaprt
Localizer.Localize(rootControl, catalog, store);
```
you will pass the rool control, which typically is the Windows Form, and localizer will recurse all child controls. As you discovered, ContextMenuStrip is not added and not part of Form.Controls collection, the Localizer will not find it.

for such case, you could simply additionally call the Localizer for the ContextMenuStrip as well:

```cshaprt
Localizer.Localize(contextMenuStrip, catalog, store);
```

> So it can be handled in the Localizer.IterateToolStripItems like as other components (the only ToolTip in the 0.9.8 version).
> Probably it would be good to have ComponentsList for all components instead of ToolTips for tooltip controls only and switch by component class in the LocalizableObjectAdapter.

not sure what the connection from Localizer.IterateToolStripItems  to ToolTip here is?

**Comment by a-sanders** [comment]
> > So it can be handled in the Localizer.IterateToolStripItems like as other components (the only ToolTip in the 0.9.8 version).
> > Probably it would be good to have ComponentsList for all components instead of ToolTips for tooltip controls only and switch by component class in the LocalizableObjectAdapter.
> 
> not sure what the connection from Localizer.IterateToolStripItems to ToolTip here is?

Sorry, it's a typo. Of course, I meant Localizer.InitFromContainer
