### ISSUE TITLE
GetText.Extractor: bug with ternary operator ?: 

### ISSUE THREAD

**Issue by a-sanders** [perpetualKid/GetText.NET#31]
When I tried to extract messages from source

```
...

toolTip.SetToolTip(pictureBox, success ? "The server was connected successfully (1)." : "The server connection failed (1).");
string test = success ? "The server was connected successfully (2)." : "The server connection failed (2).";

...
```

I was confused by the contents of the POT-file in 2 points:
```
#: .\test.cs:6
msgid ""
"The server was connected successfully (1).The server connection failed (1)."
msgstr ""
```

1) I expected that the extractor will ignore both lines but it extracts strings from the first line
2) Two strings from the first line were combined to a single message.

Command line: 
GetText.Extractor.exe --source test.cs  --target test

GetText.Extractor.exe version:
0.9.9+0d4629f2b5b010d2734feac69a4b84f57ee6695a

Appropriate source and POT files attached
[test.zip](https://github.com/perpetualKid/GetText.NET/files/6189796/test.zip)

**Comment by perpetualKid** [comment]
this is documented here>

https://github.com/perpetualKid/GetText.NET/wiki/Extractor-Limitations#conditional-expressions-need-to-be-written-as-separate-getstring-calls

https://github.com/perpetualKid/GetText.NET/wiki/Extractor-Limitations#conditional-expressions

**Comment by perpetualKid** [comment]
As to our point 1., SetToolTip is one of the terms the Extractor is looking for:

https://github.com/perpetualKid/GetText.NET/blob/f844c880e346afd1838b38e9dbe70eb9d9a91120/src/GetText.Extractor/Engine/ParserBase.cs#L21-L23

however, unlike direct assignments such as with Text/HeaderText/TooltipText properties, ternary operator is not supported in method calls, resulting in the behavior you've seen. 

Maybe worth to write some warnings in --verbose mode?

**Comment by a-sanders** [comment]
> 
> 
> this is documented here>
> 
> https://github.com/perpetualKid/GetText.NET/wiki/Extractor-Limitations#conditional-expressions-need-to-be-written-as-separate-getstring-calls
> 
> https://github.com/perpetualKid/GetText.NET/wiki/Extractor-Limitations#conditional-expressions

Sorry, but this does not apply at all to the problem that I mentioned.

**Comment by a-sanders** [comment]
> 
> 
> As to our point 1., SetToolTip is one of the terms the Extractor is looking for:
> 
> https://github.com/perpetualKid/GetText.NET/blob/f844c880e346afd1838b38e9dbe70eb9d9a91120/src/GetText.Extractor/Engine/ParserBase.cs#L21-L23
> 
> however, unlike direct assignments such as with Text/HeaderText/TooltipText properties, ternary operator is not supported in method calls, resulting in the behavior you've seen.
> 

Well... But I don't want to localize those strings. Apart from that the code placed in ordinary .cs file instead of auto-generated "*.Designer.cs" file where the Extractor should find "SetToolTip" and other points...


> Maybe worth to write some warnings in --verbose mode?

Oh, yes. It would be very useful to see more information in such ambiguous situations.

**Comment by perpetualKid** [comment]
> 
> Well... But I don't want to localize those strings. Apart from that the code placed in ordinary .cs file instead of auto-generated "*.Designer.cs" file where the Extractor should find "SetToolTip" and other points...

extractor looks for the pattern `PropertyName="Text" | "HeaderText" | "ToolTipText"` or `MethodName="SetToolTip"` regardless if thats a *.Designer.cs file or ordinary source file - all code is evaluted. 

The only solution would be to make these lists customizable/overwriteable what Methods and Properties to look for, but still it would scan both designer and other source files.

**Comment by perpetualKid** [comment]
> > this is documented here>
> > https://github.com/perpetualKid/GetText.NET/wiki/Extractor-Limitations#conditional-expressions-need-to-be-written-as-separate-getstring-calls
> > https://github.com/perpetualKid/GetText.NET/wiki/Extractor-Limitations#conditional-expressions
> 
> Sorry, but this does not apply at all to the problem that I mentioned.

I think it does, but to put in plain text:  Ternary operator is not supported in method calls, only with (Text) Property assignments.
