### ISSUE TITLE
Bug (?) with aliases requiring member syntax

### ISSUE THREAD

**Issue by Owlblocks** [perpetualKid/GetText.NET#40]
I feel really bad for not catching this sooner, but it appears that the recent changes have a caveat. While they do work, generally, the original goal of support for \_() isn't exactly met, as currently custom aliases only work if they are in a member-access syntax, e.g. ClassName._(). This means that, say, a global static using directive wouldn't allow the programmer to extract  from a method that is simply called via _().

I should be able to fix this when I have time today or maybe tomorrow, assuming it wouldn't break the code more generally.

**Comment by Owlblocks** [comment]
Any idea when a build will be published to Nuget? Or if there's a means of installing a Nuget Package from source?

**Comment by perpetualKid** [comment]
> Any idea when a build will be published to Nuget? Or if there's a means of installing a Nuget Package from source?

sorry I forgot to trigger the publish workflow, done now and new version 1.6.6 is available on Nuget https://www.nuget.org/packages/GetText.NET.Extractor/1.6.6

Thanks for update and implementation, would appreciate if the wiki gets updated as well to describe the new command line options and behavior regarding static/non-member syntax 
https://github.com/perpetualKid/GetText.NET/wiki/Extractor-CLI
