### ISSUE TITLE
GetText.Extractor output is nondetererministic

### ISSUE THREAD

**Issue by pontaoski** [perpetualKid/GetText.NET#43]
The output extractions aren't deterministic, so it's impossible to automatically use GetText.Extractor to check for if the output is up to date as the spurious changes will confuse attempts to compare new vs current output.

**Comment by perpetualKid** [comment]
> turns out this was a power of the defaults moment; the `--order` flag exists and isn't default for some reason.

GetText.Extractor was optimized for performance, so any additional processing such as sorting has to be specified explicitly. However, I realize that processing even on larger projects is fast enough so it may be worth to enforce/change some defaults.
