### ISSUE TITLE
Ignore wrongly extracted string

### ISSUE THREAD

**Issue by fsobolev** [perpetualKid/GetText.NET#50]
Hello! In a project I work on there's a line:

```
if (json.RootElement.GetProperty("result").GetString() != "success")
```

The `GetString` here is [`JsonElement.GetString`](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement.getstring?view=net-7.0) method. But GetText Extractor seems to treat this as GetText method and extracts the `result` string.
Is there a way to tell the extractor to ignore this particular line or at least a `.cs` file?

**Comment by perpetualKid** [comment]
addressed in 1759777659cd9ed8080334b5a8dc31b9eeb704b7
